In [1]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11768 entries, 0 to 11767
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Brand                 11768 non-null  object
 1   Processor             11768 non-null  object
 2   RAM (GB)              11768 non-null  int64
 3   Storage               11768 non-null  object
 4   GPU                   11768 non-null  object
 5   Screen Size (inch)    11768 non-null  float64
 6   Resolution            11768 non-null  object
 7   Battery Life (hours)  11768 non-null  float64
 8   Weight (kg)           11768 non-null  float64
 9   Operating System      11768 non-null  object
 10  Price ($)             11768 non-null  float64
dtypes: float64(4), int64(1), object(6)
memory usage: 1011.4+ KB

In [11]:
df[["Brand","Price ($)"]]

         Brand  Price ($)
0        Apple    3997.07
1        Razer    1355.78
2         Asus    2673.07
3       Lenovo     751.17
4        Razer    2059.83
...        ...        ...
11763     Acer     704.82
11764     Asus     775.59
11765    Razer    2789.46
11766  Samsung    1067.13
11767  Samsung    1579.55

[11768 rows x 2 columns]

In [17]:
df[['RAM (GB)','GPU']]

       RAM (GB)                 GPU
0            64     Nvidia GTX 1650
1             4     Nvidia RTX 3080
2            32     Nvidia RTX 3060
3             4     Nvidia RTX 3080
4             4  AMD Radeon RX 6600
...         ...                 ...
11763         4     Nvidia RTX 2060
11764         4  AMD Radeon RX 6800
11765         4  AMD Radeon RX 6600
11766        16          Integrated
11767         8     Nvidia RTX 3080

[11768 rows x 2 columns]

In [19]:
df[df['Price ($)'] >1000]

,Brand,Processor,RAM (GB),Storage,GPU,Screen Size (inch),Resolution,Battery Life (hours),Weight (kg),Operating System,Price ($)
0,Apple,AMD Ryzen 3,64,512GB SSD,Nvidia GTX 1650,17.3,2560x1440,8.9,1.42,FreeDOS,3997.07
1,Razer,AMD Ryzen 7,4,1TB SSD,Nvidia RTX 3080,14.0,1366x768,9.4,2.57,Linux,1355.78
2,Asus,Intel i5,32,2TB SSD,Nvidia RTX 3060,13.3,3840x2160,8.5,1.74,FreeDOS,2673.07
4,Razer,Intel i3,4,256GB SSD,AMD Radeon RX 6600,16.0,3840x2160,5.7,3.38,Linux,2059.83
5,Acer,AMD Ryzen 3,64,2TB SSD,Nvidia RTX 3060,14.0,1366x768,7.1,1.85,Linux,1676.64
...,...,...,...,...,...,...,...,...,...,...,...
11761,Dell,Intel i3,64,1TB SSD,AMD Radeon RX 6600,17.3,2560x1440,11.5,1.93,Windows,2683.44
11762,Apple,AMD Ryzen 9,16,1TB HDD,AMD Radeon RX 6600,15.6,1920x1080,10.9,1.55,FreeDOS,2704.23
11765,Razer,AMD Ryzen 9,4,2TB SSD,AMD Radeon RX 6600,15.6,2560x1440,8.2,2.05,Linux,2789.46
11766,Samsung,AMD Ryzen 7,16,512GB SSD,Integrated,13.3,1920x1080,7.5,1.48,macOS,1067.13
11767,Samsung,Intel i7,8,256GB SSD,Nvidia RTX 3080,17.3,2560x1440,6.4,2.45,FreeDOS,1579.55

In [9]:
#sorting values
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
df.sort_values(by = 'Price ($)', ascending = False)

,Brand,Processor,RAM (GB),Storage,GPU,Screen Size (inch),Resolution,Battery Life (hours),Weight (kg),Operating System,Price ($)
3790,Apple,AMD Ryzen 9,64,512GB SSD,AMD Radeon RX 6600,15.6,3840x2160,7.5,1.37,FreeDOS,10807.88
10436,Apple,AMD Ryzen 9,64,256GB SSD,Nvidia RTX 3080,15.6,3840x2160,5.4,1.65,FreeDOS,10774.82
11580,Apple,AMD Ryzen 9,64,1TB SSD,AMD Radeon RX 6800,16.0,3840x2160,11.6,2.78,Linux,10757.56
7609,Apple,Intel i9,64,512GB SSD,AMD Radeon RX 6800,15.6,3840x2160,11.9,3.38,FreeDOS,10735.12
5960,Apple,AMD Ryzen 9,64,2TB SSD,Nvidia RTX 3060,16.0,3840x2160,6.1,1.72,macOS,10646.06
...,...,...,...,...,...,...,...,...,...,...,...
10375,Asus,AMD Ryzen 5,4,1TB HDD,Integrated,16.0,1366x768,5.0,1.32,FreeDOS,356.10
2689,Acer,Intel i5,4,1TB HDD,Integrated,15.6,1366x768,6.8,3.34,FreeDOS,354.84
10468,Dell,Intel i3,4,1TB HDD,Integrated,17.3,1366x768,5.3,3.33,macOS,342.89
8207,Asus,AMD Ryzen 3,4,2TB SSD,Integrated,13.3,1366x768,8.8,2.69,Windows,332.71
11587,Microsoft,Intel i3,4,1TB HDD,Integrated,13.3,1366x768,4.1,2.87,Linux,279.57

In [29]:
#dropping columns
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
df.drop(columns=['Resolution','Screen Size (inch)','Battery Life (hours)','Weight (kg)', 'Operating System'], inplace = True)
print(df)

         Brand    Processor  RAM (GB)    Storage                 GPU  \
0        Apple  AMD Ryzen 3        64  512GB SSD     Nvidia GTX 1650
1        Razer  AMD Ryzen 7         4    1TB SSD     Nvidia RTX 3080
2         Asus     Intel i5        32    2TB SSD     Nvidia RTX 3060
3       Lenovo     Intel i5         4  256GB SSD     Nvidia RTX 3080
4        Razer     Intel i3         4  256GB SSD  AMD Radeon RX 6600
...        ...          ...       ...        ...                 ...
11763     Acer     Intel i3         4    2TB SSD     Nvidia RTX 2060
11764     Asus     Intel i3         4    2TB SSD  AMD Radeon RX 6800
11765    Razer  AMD Ryzen 9         4    2TB SSD  AMD Radeon RX 6600
11766  Samsung  AMD Ryzen 7        16  512GB SSD          Integrated
11767  Samsung     Intel i7         8  256GB SSD     Nvidia RTX 3080

       Price ($)
0        3997.07
1        1355.78
2        2673.07
3         751.17
4        2059.83
...          ...
11763     704.82
11764     775.59
11765    2789.46
11766    1067.13
11767    1579.55

[11768 rows x 6 columns]

In [31]:
#counting and sum null values
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
df.isnull().sum()

Brand                   0
Processor               0
RAM (GB)                0
Storage                 0
GPU                     0
Screen Size (inch)      0
Resolution              0
Battery Life (hours)    0
Weight (kg)             0
Operating System        0
Price ($)               0
dtype: int64

In [37]:
#replaces null values with 0
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
df.fillna(0, inplace=True)
print(df)

         Brand    Processor  RAM (GB)    Storage                 GPU  \
0        Apple  AMD Ryzen 3        64  512GB SSD     Nvidia GTX 1650
1        Razer  AMD Ryzen 7         4    1TB SSD     Nvidia RTX 3080
2         Asus     Intel i5        32    2TB SSD     Nvidia RTX 3060
3       Lenovo     Intel i5         4  256GB SSD     Nvidia RTX 3080
4        Razer     Intel i3         4  256GB SSD  AMD Radeon RX 6600
...        ...          ...       ...        ...                 ...
11763     Acer     Intel i3         4    2TB SSD     Nvidia RTX 2060
11764     Asus     Intel i3         4    2TB SSD  AMD Radeon RX 6800
11765    Razer  AMD Ryzen 9         4    2TB SSD  AMD Radeon RX 6600
11766  Samsung  AMD Ryzen 7        16  512GB SSD          Integrated
11767  Samsung     Intel i7         8  256GB SSD     Nvidia RTX 3080

       Screen Size (inch) Resolution  Battery Life (hours)  Weight (kg)  \
0                    17.3  2560x1440                   8.9         1.42
1                    14.0   1366x768                   9.4         2.57
2                    13.3  3840x2160                   8.5         1.74
3                    13.3   1366x768                  10.5         3.10
4                    16.0  3840x2160                   5.7         3.38
...                   ...        ...                   ...          ...
11763                17.3   1366x768                  11.5         1.58
11764                16.0   1366x768                   9.5         2.14
11765                15.6  2560x1440                   8.2         2.05
11766                13.3  1920x1080                   7.5         1.48
11767                17.3  2560x1440                   6.4         2.45

      Operating System  Price ($)
0              FreeDOS    3997.07
1                Linux    1355.78
2              FreeDOS    2673.07
3              Windows     751.17
4                Linux    2059.83
...                ...        ...
11763            macOS     704.82
11764            Linux     775.59
11765            Linux    2789.46
11766            macOS    1067.13
11767          FreeDOS    1579.55

[11768 rows x 11 columns]

In [39]:
#dropping null values in a data set and updating to the original dataset
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
df.dropna(inplace=True)
print(df)
df.to_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csvr",index=False)

         Brand    Processor  RAM (GB)    Storage                 GPU  \
0        Apple  AMD Ryzen 3        64  512GB SSD     Nvidia GTX 1650
1        Razer  AMD Ryzen 7         4    1TB SSD     Nvidia RTX 3080
2         Asus     Intel i5        32    2TB SSD     Nvidia RTX 3060
3       Lenovo     Intel i5         4  256GB SSD     Nvidia RTX 3080
4        Razer     Intel i3         4  256GB SSD  AMD Radeon RX 6600
...        ...          ...       ...        ...                 ...
11763     Acer     Intel i3         4    2TB SSD     Nvidia RTX 2060
11764     Asus     Intel i3         4    2TB SSD  AMD Radeon RX 6800
11765    Razer  AMD Ryzen 9         4    2TB SSD  AMD Radeon RX 6600
11766  Samsung  AMD Ryzen 7        16  512GB SSD          Integrated
11767  Samsung     Intel i7         8  256GB SSD     Nvidia RTX 3080

       Screen Size (inch) Resolution  Battery Life (hours)  Weight (kg)  \
0                    17.3  2560x1440                   8.9         1.42
1                    14.0   1366x768                   9.4         2.57
2                    13.3  3840x2160                   8.5         1.74
3                    13.3   1366x768                  10.5         3.10
4                    16.0  3840x2160                   5.7         3.38
...                   ...        ...                   ...          ...
11763                17.3   1366x768                  11.5         1.58
11764                16.0   1366x768                   9.5         2.14
11765                15.6  2560x1440                   8.2         2.05
11766                13.3  1920x1080                   7.5         1.48
11767                17.3  2560x1440                   6.4         2.45

      Operating System  Price ($)
0              FreeDOS    3997.07
1                Linux    1355.78
2              FreeDOS    2673.07
3              Windows     751.17
4                Linux    2059.83
...                ...        ...
11763            macOS     704.82
11764            Linux     775.59
11765            Linux    2789.46
11766            macOS    1067.13
11767          FreeDOS    1579.55

[11768 rows x 11 columns]

In [53]:
#sum of values in columns
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Downloads\archive(5)\laptop_prices.csv")
def sum_columns(df):
    return df[['RAM (GB)','Price ($)']].sum()
total_sum = sum_columns(df)
print(total_sum)

RAM (GB)       292468.00
Price ($)    25696270.68
dtype: float64